# Generated by Django 3.0.4 on 2020-03-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='name',
        ),
    ]
